# Generated by Django 5.1.1 on 2024-10-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Número de teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Barrio')),
                ('companies', models.ManyToManyField(to='companies.company')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
