# Generated by Django 5.1.1 on 2024-10-10 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de la empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document_types.documenttype', verbose_name='Tipo de documento')),
            ],
        ),
    ]
