# Generated by Django 5.1.1 on 2024-10-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_types', '0002_alter_documenttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
