# Generated by Django 5.1.1 on 2024-10-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='images/', verbose_name='Imagen'),
        ),
    ]
